name: demo_flutter
description: Demo Flutter

dependencies:
  flutter_svg:
  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  photo_view: ^0.9.1
  carousel_slider: ^1.4.1
  qr_code_scanner: ^0.0.12
  toast: ^0.1.5
  youtube_player_flutter: ^6.0.3+2
  shared_preferences: ^0.5.6+1
  flutter_bloc: ^3.1.0
  equatable: ^1.0.1
  json_annotation: ^3.0.0
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  build_runner: ^1.7.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts: 
    - family: PTSans 
      fonts:
        - asset: assets/fonts/ptasans-regular.ttf
        - asset: assets/fonts/ptasans-bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
